

import React from 'react'
import { Navegador } from './Navegador'
import { Footer } from './Footer'
import Head from 'next/head'



export const Layout = ({children}) => {
  return (
    <>
        <Navegador/>
        <Head>
            <title>Antena 9</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />

            
        </Head>

        {children}

        <Footer />
    </>
  )
}
