import Head from 'next/head'
import Image from 'next/image'
import {Navegador} from '../components/Navegador'


export default function Nosotros() {
  return (
    <>
      <Head>
        <title>Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto'>
        <Navegador />
        <h1> Nosotros</h1>
        
      </main>
    </>
  )
}
